### ISSUE TITLE
Support Exit Networks

### ISSUE THREAD

**Issue by ekampf** [Twingate/terraform-provider-twingate#586] opened 2024-09-30 18:44 UTC
Add `exit_node` field to `twingate_remote_network` - default to `False` and field is immutable (once set, changing it requires recreating the network)

We're still contemplating wether this should be a whole separate `twingate_exit_network` resource type but we can do the work above and then decide later...

**Comment by alexb-twingate** [comment] 2024-11-22 00:20
Replaced by/duplicate of #604

**Closed by alexb-twingate** 2024-11-22 00:20 UTC
Labels: onhold
