### ISSUE TITLE
Feature Request: Support for Setting Expiration Dates on Twingate Service Account Keys in Terraform

### ISSUE THREAD

**Issue by TylerStaplerAtFanatics** [Twingate/terraform-provider-twingate#355] opened 2023-07-03 21:19 UTC
## Description:
We currently use the Terraform provider for Twingate to create service account keys. However, we've noticed that there's no option to set an expiration date for these keys. For better key management and security, we'd like to request the addition of a feature that allows setting an expiration date for service account keys in Terraform.

Existing resource https://registry.terraform.io/providers/Twingate/twingate/1.0.0-rc2/docs/resources/service_account_key

## Use case:
We want to manage and rotate keys through Terraform. Setting an expiration date for the keys would help us automate the process of key rotation, enhancing our system's security by ensuring that old keys become invalid after a certain period.

## Potential solution:
Add a new optional parameter to the service_account_key resource that allows setting an expiration date for the key.

Thank you for considering this feature request. Please let us know if there's any additional information we can provide.

**Comment by ekampf** [comment] 2023-08-10 17:53
Hey @TylerStaplerAtFanatics !
Thanks for the feedback - we definitely plan to add this support very soon...

**Comment by TylerStaplerAtFanatics** [comment] 2023-08-29 19:33
Hey Alex thanks for the follow-up.

 I think the second option would be easiest to manage. Most likely we would have two service accounts that have overlapping validity so that we can migrate clients to the new key before it expires.

There may be a way to create a resource which does this automatically, by having a primary and a secondary key, and specifying when you want to "renew" but that would change the current API somewhat drastically.

**Comment by alexb-twingate** [comment] 2023-08-29 19:36
Yeah, we would updating the public API to support the first option if it's the way to go. For now, we'll pursue the second one. Thanks so much!

**Comment by tjstansell** [comment] 2023-08-30 19:01
After having thought through this a bit on what the process would look like (and I've even mocked up a potential module definition for auto rotation/cycling of a pair of keys for a service account), I feel like the setting of the expiration date should be separately controlled from the cycling of the resource.  It should be entirely possible to do something like this:
```hcl
resource "twingate_service_account_key" "B" {
  name               = var.name_prefix == null ? "B" : "${var.name_prefix} B"
  service_account_id = var.service_account_id
  expire_days        = var.rotation_days * 2

  lifecycle {
    replace_triggered_by = time_offset.next_B.rfc3339
  }
}
```
Where the `time_offset` resource changing is what's controlling _when_ the key gets recreated, but when that does happen, it'll use a static offset in days for when the key should expire.  If you'd like to have a way to force the resource to be triggered without relying on the lifecycle feature, you could introduce a `triggers = {}` map that can control that.  This is already a well established pattern used by resources like `time_offset`, `null_resource`, `aws_lambda_invocation`, etc.  See [google_service_account_key](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_key#example-usage-creating-and-regularly-rotating-a-key) as another example, but they call it `keepers = {}`.

**Comment by alexb-twingate** [comment] 2023-09-07 18:33
Duplicate of #390 - we can continue the conversation in that ticket.

**Closed by alexb-twingate** 2023-09-07 18:33 UTC
Labels: enhancement

**Comment by alexb-twingate** [comment] 2023-09-07 18:36
Duplicate of #390
