### ISSUE TITLE
Error getting remote network ID from data source in inconsistent way

### ISSUE THREAD

**Issue by oscarboher** [Twingate/terraform-provider-twingate#612] opened 2024-12-03 15:37 UTC
Hi!

We are using the twingate provider to create resources in remote networks managed in other terraform states.

We use the data source "twingate_remote_network" with the name to get the network ID to use in the twingate_resource `remote_network_id`.
The name of the twingate network is formed using other data sources from a cloud provider in order to find the correct one.

We have seen that when doing a terraform plan, the data source returns an object where the ID is null, and in it's turn, the twingate_resource fails as the `remote_network_id` cannot be null. If I hardcode the network name, the object returned does have the ID field, even tho the name is exactly the same.
We have also seen that this does not seem to happen consistently as we have been able to run successful plans and applies. The only thing we have noticed is that for terraform states that have little changes or that are small this seems to work fine, but when the state is bigger and the plan involves checking many resources this seems to fail more consistently.

Is there any explanation on why we are seeing this "random" behavior? If getting the network ID using the data source with a name formed by other data sources was not supported, this should fail consistently on our module tests, but those are executed just fine.

We are using the latest twingate terraform provider.

Thank you!

**Comment by vmanilo** [comment] 2024-12-03 21:12
hey @oscarboher 

if you could share code example similar to one you have, we can try reproduce the issue.

Currently I can just suggest to add `depends_on` list with resources/datasources on which your remote_network datasource depends for resolving the input name, and see if this "random" behavior still exists.

Here is a simple  example:
```
resource "twingate_group" "group_1" {
  name = "g1"
}

resource "twingate_group" "group_2" {
  name = "g2"
}

data "twingate_remote_network" "test" {
  name = format("network_%s_%s", resource.twingate_group.group_1.name, resource.twingate_group.group_2.name)

  depends_on = [resource.twingate_group.group_1, resource.twingate_group.group_2]
}
```

**Comment by oscarboher** [comment] 2024-12-04 09:02
Hi @vmanilo , 

I added the depends_on and it seems to fix the issue and have a consistent behavior, being able to resolve the network ID now. Thank you!!

For reference, the code simplified was something like this:

```

data "aws_vpc" "my_vpc" {
  id = var.vpc_id
}


data "twingate_remote_network" "remote_network" {
  name = "${var.remote_network_prefix}_${aws_vpc.my_vpc.tags.Name}_${aws_vpc.my_vpc.id}"
}


resource "twingate_resource" "resource" {
  remote_network_id = data.twingate_remote_network.remote_network.id
  ...
}
```

adding the depends on worked:
```
data "twingate_remote_network" "remote_network" {
  name = "${var.remote_network_prefix}_${data.aws_vpc.my_vpc.tags.Name}_${data.aws_vpc.my_vpc.id}"

  depends_on = [data.aws_vpc.my_vpc]
}
```

I checked the terraform dependency graph with and without the explicit dependency and they look the same. Any idea why this might happen?

**Comment by vmanilo** [comment] 2024-12-06 19:39
@oscarboher you're right in this scenario there is no other options for dependency graph, 
I'm not really sure what can cause different result

but from what I've read on forums, it's just recommendation to add `depends_on` section, when dependencies doesn't work as expected.

Maybe you can reach out terraform guys directly, because it's really out of scope of Twingate provider, we don't have control  over dependency resolution.

**Closed** 2024-12-09 08:18 UTC
